"""Cross-platform app auto-start helpers (PyInstaller build focused)."""

from __future__ import annotations

import platform
import shlex
import subprocess
import sys
import os
from pathlib import Path

APP_NAME = "MahiroSearch"
_WINDOWS_RUN_KEY = r"Software\Microsoft\Windows\CurrentVersion\Run"
_MACOS_LABEL = "com.mahirosearch.app"


def _project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _packaged_executable() -> Path | None:
    """Locate packaged executable generated by PyInstaller."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable)

    root = _project_root()
    system = platform.system()

    if system == "Windows":
        candidates = [
            root / "dist" / "MahiroSearch" / "MahiroSearch.exe",
            root / "dist" / "MahiroSearch.exe",
        ]
    elif system == "Linux":
        candidates = [
            root / "dist" / "MahiroSearch" / "MahiroSearch",
            root / "dist" / "MahiroSearch",
        ]
    elif system == "Darwin":
        candidates = [
            root / "dist" / "MahiroSearch.app" / "Contents" / "MacOS" / "MahiroSearch",
            root / "dist" / "MahiroSearch" / "MahiroSearch",
            root / "dist" / "MahiroSearch",
        ]
    else:
        candidates = []

    for c in candidates:
        if c.exists():
            return c
    return None


def _launch_command_for_autostart() -> str:
    exe = _packaged_executable()
    if exe is None:
        raise RuntimeError("未找到打包后的可执行文件，请先运行 build_windows.py / build_linux.py / build_macos.py")
    return f'"{exe}"'


def _linux_desktop_file() -> Path:
    return Path.home() / ".config" / "autostart" / "mahirosearch.desktop"


def _macos_launch_agent_file() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{_MACOS_LABEL}.plist"


def is_enabled() -> bool:
    system = platform.system()
    if system == "Windows":
        return _is_windows_enabled_hklm() or _is_windows_enabled_hkcu()
    if system == "Linux":
        return _linux_desktop_file().exists()
    if system == "Darwin":
        return _macos_launch_agent_file().exists()
    return False


def set_enabled(enabled: bool) -> None:
    """Apply immediately."""
    system = platform.system()
    if system == "Windows":
        _set_windows(enabled)
        return
    if system == "Linux":
        _set_linux(enabled)
        return
    if system == "Darwin":
        _set_macos(enabled)
        return
    raise NotImplementedError(f"Auto-start is not implemented for {system}")


def ensure(enabled: bool) -> None:
    """Best-effort sync with expected state from config at app startup."""
    try:
        current = is_enabled()
        if current != enabled:
            set_enabled(enabled)
    except Exception:
        pass


def _is_windows_admin() -> bool:
    import ctypes

    try:
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    except Exception:
        return False


def _is_windows_enabled_hklm() -> bool:
    import winreg

    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, _WINDOWS_RUN_KEY, 0, winreg.KEY_READ) as key:
            value, _ = winreg.QueryValueEx(key, APP_NAME)
            return bool(value)
    except Exception:
        return False


def _is_windows_enabled_hkcu() -> bool:
    import winreg

    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _WINDOWS_RUN_KEY, 0, winreg.KEY_READ) as key:
            value, _ = winreg.QueryValueEx(key, APP_NAME)
            return bool(value)
    except Exception:
        return False


def _set_windows(enabled: bool) -> None:
    # Enabling requires launch command from packaged executable.
    launch_command = _launch_command_for_autostart() if enabled else ""

    if _is_windows_admin():
        _set_windows_registry_hklm(enabled, launch_command)
        _clear_windows_hkcu_legacy()
        return

    _set_windows_via_uac(enabled, launch_command)


def _set_windows_registry_hklm(enabled: bool, launch_command: str) -> None:
    import winreg

    with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, _WINDOWS_RUN_KEY, 0, winreg.KEY_SET_VALUE) as key:
        if enabled:
            winreg.SetValueEx(key, APP_NAME, 0, winreg.REG_SZ, launch_command)
            return
        try:
            winreg.DeleteValue(key, APP_NAME)
        except FileNotFoundError:
            pass


def _clear_windows_hkcu_legacy() -> None:
    import winreg

    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _WINDOWS_RUN_KEY, 0, winreg.KEY_SET_VALUE) as key:
            try:
                winreg.DeleteValue(key, APP_NAME)
            except FileNotFoundError:
                pass
    except Exception:
        pass


def _set_windows_via_uac(enabled: bool, launch_command: str) -> None:
    if enabled:
        reg_script = (
            "New-Item -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Force | Out-Null; "
            f"Set-ItemProperty -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name '{APP_NAME}' -Value '{_ps_quote(launch_command)}'"
        )
    else:
        reg_script = (
            f"Remove-ItemProperty -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name '{APP_NAME}' -ErrorAction SilentlyContinue"
        )

    cmd = (
        "$script = @'\n"
        f"{reg_script}\n"
        "'@; "
        "$p=Start-Process -FilePath 'powershell' "
        "-ArgumentList @('-NoProfile','-Command',$script) -Verb RunAs -Wait -PassThru; "
        "exit $p.ExitCode"
    )

    result = subprocess.run(["powershell", "-NoProfile", "-Command", cmd], check=False)
    if result.returncode != 0:
        raise PermissionError("管理员提权失败或被取消")


def _ps_quote(value: str) -> str:
    return value.replace("'", "''")


def _set_linux(enabled: bool) -> None:
    desktop_file = _linux_desktop_file()
    if enabled:
        desktop_file.parent.mkdir(parents=True, exist_ok=True)
        cmd = _launch_command_for_autostart()
        exec_cmd = " ".join(shlex.quote(part) for part in shlex.split(cmd))
        desktop_file.write_text(
            "\n".join(
                [
                    "[Desktop Entry]",
                    "Type=Application",
                    f"Name={APP_NAME}",
                    f"Exec={exec_cmd}",
                    "X-GNOME-Autostart-enabled=true",
                    "Terminal=false",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        return

    if desktop_file.exists():
        desktop_file.unlink()


def _set_macos(enabled: bool) -> None:
    plist = _macos_launch_agent_file()
    uid = str(os.getuid())
    domain = f"gui/{uid}"

    if enabled:
        plist.parent.mkdir(parents=True, exist_ok=True)
        exe = _packaged_executable()
        if exe is None:
            raise RuntimeError("未找到打包后的可执行文件，请先运行 build_macos.py")

        plist.write_text(
            "\n".join(
                [
                    '<?xml version="1.0" encoding="UTF-8"?>',
                    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
                    '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
                    '<plist version="1.0">',
                    "<dict>",
                    "<key>Label</key>",
                    f"<string>{_MACOS_LABEL}</string>",
                    "<key>ProgramArguments</key>",
                    "<array>",
                    f"<string>{exe}</string>",
                    "</array>",
                    "<key>RunAtLoad</key>",
                    "<true/>",
                    "<key>KeepAlive</key>",
                    "<false/>",
                    "</dict>",
                    "</plist>",
                    "",
                ]
            ),
            encoding="utf-8",
        )

        subprocess.run(
            ["launchctl", "bootout", domain, str(plist)],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        subprocess.run(
            ["launchctl", "bootstrap", domain, str(plist)],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        subprocess.run(
            ["launchctl", "enable", f"{domain}/{_MACOS_LABEL}"],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return

    subprocess.run(
        ["launchctl", "bootout", domain, str(plist)],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if plist.exists():
        plist.unlink()
